In [3]:
import os
import shutil

In [159]:
with open('split/t2_ft.txt', 'r') as f:
    data = f.readlines()
data_prefixes = [item.strip() for item in data]

jpg_files = os.listdir('datasets/t1/images/train')
jpg_prefixes = [os.path.splitext(file)[0].lower() for file in jpg_files]

source_folder= 'datasets/t1/images/train'
destination_folder= 'datasets/t2_ft/images/train'
for filename in jpg_prefixes:
    filenameJpg = filename + '.jpg'
    if filename in data_prefixes and not os.path.exists(os.path.join(destination_folder,filenameJpg)):
        source_path = os.path.join(source_folder, filenameJpg)
        shutil.copy(source_path,destination_folder)

In [35]:
with open('split/t1_train.txt', 'r') as f:
    data = f.readlines()
data_prefixes = [item.strip() for item in data]

In [40]:
jpg_files = os.listdir('datasets/t1/images/train')
jpg_prefixes = [os.path.splitext(file)[0].lower() for file in jpg_files]

In [7]:
print(16551+45520+39402+40260)

141733


In [38]:
len(data_prefixes)

16551

In [41]:
len(jpg_prefixes)

143041

In [155]:
missing_files = set(data_prefixes) - set(jpg_prefixes)
missing_files = list(missing_files)
print('TXT:',len(data_prefixes),'JPG:',len(jpg_prefixes), 'MISSING:', len(missing_files))

TXT: 2749 JPG: 143041 MISSING: 0


In [9]:
jpg_files = os.listdir('datasets/t1/images/test')
jpg_prefixes = [os.path.splitext(file)[0].lower() for file in jpg_files]

source_folder= 'datasets/t1/images/test'
destination_folder= 'datasets/t2/images/test'
for filename in jpg_prefixes:
    filenameJpg = filename + '.jpg'
    source_path = os.path.join(source_folder, filenameJpg)
    shutil.copy(source_path,destination_folder)

In [3]:
#checking
with open('split/all_task_test.txt', 'r') as f:
    data = f.readlines()
data_prefixes = [item.strip() for item in data]

jpg_files = os.listdir('datasets/t1/images/test')
jpg_prefixes = [os.path.splitext(file)[0].lower() for file in jpg_files]
missing_files = set(data_prefixes) - set(jpg_prefixes)
missing_files = list(missing_files)
print('TXT:',len(data_prefixes),'JPG:',len(jpg_prefixes), 'MISSING:', len(missing_files))

TXT: 10246 JPG: 9952 MISSING: 0


In [1]:
import torch


In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda.device_count()

4

In [4]:
torch.tensor([1, 2, 3, 4], device='cuda')

tensor([1, 2, 3, 4], device='cuda:0')

In [2]:
import torch

In [34]:
x_dic = torch.rand((10000,4))
x_meta = torch.arange(start=-2,end=2,step=0.4)

In [42]:
x_dic[1][3]

tensor(0.2571)

In [47]:
x_dic[torch.randperm(x_dic.size(0))]

tensor([[0.0245, 0.5429, 0.5017, 0.5101],
        [0.0121, 0.0188, 0.2528, 0.6183],
        [0.0363, 0.2514, 0.9266, 0.2487],
        ...,
        [0.3710, 0.1542, 0.4014, 0.1297],
        [0.3951, 0.8283, 0.7753, 0.8947],
        [0.1025, 0.5294, 0.8524, 0.4669]])

In [31]:
x_dic[1000+100+10+1][0]

tensor(0.5617)

In [32]:
x_dic[1000+100+10+1][0]=x_meta[1]

In [33]:
x_dic[1000+100+10+1][0]

tensor(-1.6000)

In [23]:
for i1 in range(10):
    for i2 in range(10):
        for i3 in range(10):
            for i4 in range(10):
                 x_dic[i1*1000+i2*100+i3*10+i4][0],x_dic[i1*1000+i2*100+i3*10+i4][1],x_dic[i1*1000+i2*100+i3*10+i4][2],x_dic[i1*1000+i2*100+i3*10+i4][3] = x_meta[i1],x_meta[i2],x_meta[i3],x_meta[i4]
x_dic = x_dic[torch.randperm(x_dic.size(0))]

In [24]:
x_dic

tensor([[-2.0000e+00, -1.6000e+00,  4.0000e-01, -1.2000e+00],
        [-8.0000e-01, -1.6000e+00, -2.0000e+00,  1.2000e+00],
        [ 4.0000e-01,  8.0000e-01,  1.6000e+00,  8.0000e-01],
        ...,
        [ 8.0000e-01,  1.2000e+00,  4.0000e-01, -2.0000e+00],
        [ 1.2000e+00, -1.2000e+00, -1.2000e+00,  1.1102e-16],
        [-1.6000e+00, -4.0000e-01, -2.0000e+00,  1.6000e+00]])

In [ ]:
device = torch.device('cpu')

In [50]:
t = torch.randint(0, 1000, (1,)).long()

In [51]:
t

tensor([602])

In [52]:
x = torch.randn(1000, 4)

In [53]:
x

tensor([[-0.3999, -0.1084, -0.3614, -1.2144],
        [ 0.4294,  0.5482,  0.5486,  0.2227],
        [-0.1483,  0.5492, -0.8637,  0.4882],
        ...,
        [ 1.8766, -2.2535, -0.4195,  0.9122],
        [-1.5240,  1.5395,  0.5514, -0.1140],
        [ 0.3363, -0.6876, -0.1506,  1.4572]])